"""Add colunm

Revision ID: 108edd0dad97
Revises: f142f105c2b5
Create Date: 2023-03-24 10:21:07.570177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "108edd0dad97"
down_revision = "f142f105c2b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("custom_transfer_id", sa.String(length=150), nullable=False)
        )
        batch_op.add_column(sa.Column("create_at", sa.DateTime(), nullable=False))
        batch_op.drop_column("create_on")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "create_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("create_at")
        batch_op.drop_column("custom_transfer_id")

    # ### end Alembic commands ###
