"""Add transactions table

Revision ID: f142f105c2b5
Revises: 9225754c7ba8
Create Date: 2023-03-24 10:01:20.528177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f142f105c2b5"
down_revision = "9225754c7ba8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.String(length=100), nullable=False),
        sa.Column("transfer_id", sa.String(length=100), nullable=False),
        sa.Column("target_account_id", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("create_on", sa.DateTime(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("complaint_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
