name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: requirements.txt

