name: Flask insurence services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: soxa
          POSTGRES_DB: InsurenceServicesTestDB
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies and test
      env:
        DB_USER: "postgres"
        DB_PASSWORD: 'soxa'
        DB_PORT: '5432'
        DB_NAME: 'InsurenceServicesTestDB'
        SECRET_KEY: ""
        AWS_ACCESS_KEY: ""
        AWS_SECRET: ""
        AWS_BUCKET: ""
        AWS_REGION: ""
        WISE_TOKEN: ""
        WISE_URL: ""
        POSTGRES_PASSWORD: soxa
        POSTGRES_USER: postgres
        POSTGRES_DB: InsurenceServicesTestDB
      run: |
        cd Lecture4-Complaints-system
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PGPASSWORD="soxa"
        pytest
    - name: Check packages for vulnerability
      pip-audit:
        steps:
          - uses: pypa/gh-action-pip-audit@v1.0.0
            with:
              inputs: requirements.txt
    - name: Standardize(PEP8) code using module Black
      lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: psf/black@stable
